# Generated by Django 5.1.6 on 2025-07-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_recommendedcontent_related_element_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedcontent',
            name='show_on_temperament_page',
            field=models.BooleanField(default=False, help_text='Bu içerik ilgili mizaç detay sayfasında (örn: air_more.html) özel öneriler bölümünde gösterilsin mi? Her mizaç için en fazla 3 adet seçmeniz önerilir.', verbose_name='Mizaç Sayfasında Göster'),
        ),
    ]
