# Generated by Django 5.1.6 on 2025-07-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_add_temperament_page_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedcontent',
            name='image',
            field=models.ImageField(blank=True, help_text="PNG, JPG veya WebP formatında yükleyebilirsiniz. Otomatik olarak WebP'ye dönüştürülecek ve optimize edilecek.", null=True, upload_to='content_images/', verbose_name='Görsel'),
        ),
    ]
