# Generated by Django 5.1.7 on 2025-05-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_algorithm', '0011_category_testresult_created_at_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.RemoveField(
            model_name='content',
            name='element_types',
        ),
        migrations.RemoveField(
            model_name='content',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='content',
            name='saved_by',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
